name: learningx_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.10
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  get: 4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.2
  timezone: ^0.9.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
